[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
solc = "0.8.23"
test = "test"
optimizer = true
optimizer_runs = 1000


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.test]
via-ir = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
